### ISSUE TITLE
TypeError: $.map is not a function

### ISSUE THREAD

**Issue by kobimx** [chrisChatzi/ajax-query#1]
Hi, i'm having a problem using your module. currently i'm trying to use it to make ajax requests into the main process because i don't have a renderer process since i'm doing a tray only app with no windows. when i try to run it i get a

``` javascript
TypeError: $.map is not a function
    at Object.ajaxClass.checkIfExists (/Users/mirko/Google Drive/nodeApp/tray/node_modules/ajax-query/ajax.js:82:19)
    at Object.ajaxClass.setType (/Users/mirko/Google Drive/nodeApp/tray/node_modules/ajax-query/ajax.js:43:35)
    at Object.ajaxClass.settings (/Users/mirko/Google Drive/nodeApp/tray/node_modules/ajax-query/ajax.js:30:22)
    at Object.ajaxClass.init (/Users/mirko/Google Drive/nodeApp/tray/node_modules/ajax-query/ajax.js:24:22)
    at Object.ajaxRequest (/Users/mirko/Google Drive/nodeApp/tray/node_modules/ajax-query/ajax.js:125:22)
    at EventEmitter.<anonymous> (/Users/mirko/Google Drive/nodeApp/tray/main.js:23:10)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
```

error. is it beacuse jquery needs a browser window therefore some html to work?
could i potentially make it work without a window open?

**Comment by chrisChatzi** [comment]
Hello,

No, I don't think that you need a browser window, that must not be the problem.
Can you show me how you call the _ajaxRequest_ method?
Also can you try calling the _ajaxSetHeaders_ method? This method also uses a $.map function and it would be interesting to see if you get the same error.

Regards
Christos
